version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/angular"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/src/python"
    schedule:
      interval: "weekly"
    target-branch: "develop"
