[tool.poetry]
name = "seedsync"
version = "0.0.0"
description = "File synchronization tool for seedboxes"
authors = []

[tool.poetry.dependencies]
python = "^3.8"
bottle = ">=0.12,<1.0"
paste = ">=3.0"
patool = ">=1.12"
pexpect = ">=4.8"
requests = ">=2.32.0"
tblib = ">=3.0"
timeout-decorator = ">=0.5"
urllib3 = ">=2.2.0"
certifi = ">=2024.7.4"

[tool.poetry.group.dev.dependencies]
pyinstaller = ">=6.0"
pytest = ">=7.0"
parameterized = "*"
testfixtures = "*"
webtest = "*"
